In [ ]:
import numpy as np

In [ ]:
# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

l = [0,1,2,3,4,5]
arr = np.array(l)
arr.dtype

dtype('int64')

In [ ]:
# 2. Given a NumPy array 'arr', check if its data type is float64.
arr = np.array([1.5, 2.6, 3.7])
arr.dtype

dtype('float64')

In [ ]:
#3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
arr = np.array([1+2j, 2+3j, 3+4j])
arr

array([1.+2.j, 2.+3.j, 3.+4.j])

In [ ]:
# 4. Convert an existing NumPy array 'arr' of integers to float32 data type.
l = [0,1,2,3,4,5]
arr = np.array(l)
arr1=np.float32(arr)
arr1
arr1.dtype

dtype('float32')

In [ ]:
# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
arr = np.array([1.5, 2.6, 3.7])
arr2 = np.float32(arr)
arr2.dtype

dtype('float32')

In [ ]:
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.


l = [0,1,2,3,4,5]
arr = np.array(l)

def array_attributes(arr):
  print ("The shape of array :", arr.size) #check the shape of array1
  print ("The size of array :", arr.shape) #check the size of array1
  print ("The data type of array :", arr.dtype) #check the data type of array1

In [ ]:
array_attributes(arr)

The shape of array : 6
The size of array : (6,)
The data type of array : int64


In [ ]:
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

a = np.ones((3,4))
a
def array_dimension(a):
  print ("The dimension of array :", a.ndim) #check the dimension of array1

In [ ]:
array_dimension(a)

The dimension of array : 2


In [ ]:
# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.
# create a numpy 1d-array
x = np.array([100,20,34])

print("Size of the array: ",
      x.size)

print("Memory size of one array element in bytes: ",
      x.itemsize)

# memory size of numpy array in bytes
print("Memory size of numpy array in bytes:",
      x.size * x.itemsize)

print("Memory size of a NumPy array:",
      x.nbytes)

Size of the array:  3
Memory size of one array element in bytes:  8
Memory size of numpy array in bytes: 24
Memory size of a NumPy array: 24


In [ ]:
# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

def array_strides(a):
  print ("The strides of array :", a.strides) #check the strides of array1

In [ ]:
array_strides(np.array([100,20,34]))

The strides of array : (8,)


In [ ]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array
def shape_stride_relationship(a):
  print ("The shape of array :", a.shape) #check the shape of array1
  print ("The strides of array :", a.strides) #check the strides of array1

shape_stride_relationship(np.array([100,20,34]))

The shape of array : (3,)
The strides of array : (8,)


In [ ]:
# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.
def create_zeros_array(n):
  print ("The shape of array :", np.zeros(n))
create_zeros_array((3,4))

The shape of array : [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.
def create_ones_matrix(n):
  print (np.ones(n))
create_ones_matrix((3,4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified`step`.
def generate_range_array(start,stop,step):
  print (np.arange(start,stop,step))   # menthod no-1

generate_range_array(1,10,2)

[1 3 5 7 9]


In [ ]:
def generate_range_array(a): #method #2
  print (np.array(a))
generate_range_array(list(range(0,10,2)))

[0 2 4 6 8]


In [ ]:
# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop`(inclusive).
def generate_linear_space(start,stop,num):
  print (np.linspace(start,stop,num))
generate_linear_space(1,10,5)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.
def create_identity_matrix(n):
  print (np.eye(n))
create_identity_matrix(3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 16. Write a function that takes a Python list and converts it into a NumPy array.
l = [1,2,3,4,5,6,7]

def convert_list_to_array(l):
  print (np.array(l))
convert_list_to_array(l)

[1 2 3 4 5 6 7]


In [ ]:
# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
array1 = np.array([1,2,3,4,5])
array2 = array1.view()

print (array2)

[1 2 3 4 5]


In [ ]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])
np.concatenate((a,b),axis=1)

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`
a = np.ones([3,3])
b = np.zeros([3,4])
np.concatenate((a,b), axis=1)

array([1, 2, 3, 4, 5, 6])

In [ ]:
# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
def generate_range_array(start,stop,step):
  print (np.arange(start,stop,step))   # menthod no-1

generate_range_array(1,10,2)

[1 3 5 7 9]


In [ ]:
# 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
def generate_linear_space(start,stop,num):
  print (np.linspace(start,stop,num))
generate_linear_space(0,1,10)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive)
def generate_logspace(start,stop,num):
  print (np.logspace(start,stop,num))
generate_logspace(1,1001,5)

[1.e+001 1.e+251     inf     inf     inf]


/usr/local/lib/python3.10/dist-packages/numpy/core/function_base.py:298: RuntimeWarning: overflow encountered in power
  return _nx.power(base, y)


In [ ]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100
import pandas as pd
df = pd.DataFrame(np.random.randint(1,100,(5,3)))
df

0   1   2
0  98  80  26
1  88  88  70
2  64  53  91
3  88  17  84
4  60   5  71

In [ ]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.
# importing pandas module
import pandas as pd

# Creating pandas DataFrame
df = pd.DataFrame({"A": [1, 2, -3, 4, -5, 6],
                   "B": [3, -5, -6, 7, 3, -2],
                   "C": [-4, 5, 6, -7, 5, 4],
                   "D": [34, 5, 32, -3, -56, -54]})
df #original dataframe

A  B  C   D
0  1  3 -4  34
1  2 -5  5   5
2 -3 -6  6  32
3  4  7 -7  -3
4 -5  3  5 -56
5  6 -2  4 -54

In [ ]:
df[df< 0] = 0 #replace negative values with 0
df

A  B  C   D
0  1  3  0  34
1  2  0  5   5
2  0  0  6  32
3  4  7  0   0
4  0  3  5   0
5  6  0  4   0

In [ ]:
# 26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
arr[2]

30

In [ ]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[1,2]

6

In [ ]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])
arr[arr>5]

array([ 8, 10,  7])

In [ ]:
# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:6]

array([3, 4, 5, 6])

In [ ]:
# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_2d[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [ ]:
# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
indices = np.array([[0, 1],
                    [2, 0]])
arr_2d[indices]

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [1, 2, 3]]])

In [ ]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
threshold = 5
arr[arr > threshold]

array([6, 7, 8, 9])

In [ ]:
# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
arr_3d = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
indices1 = np.array([0, 0])
indices2 = np.array([1, 1])
arr_3d[indices1, indices2]

array([[3, 4],
       [3, 4]])

In [ ]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
condition1 = arr % 2 == 0
condition2 = arr > 5
arr[condition1 & condition2]

array([6, 8])

In [ ]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
indices1 = np.array([0, 1])
indices2 = np.array([0, 2])
arr_2d[indices1, indices2]

array([1, 6])

In [ ]:
# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr + 5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6, 7],
                [8, 9, 10, 11],
                [12, 13, 14, 15]])
np.multiply(arr1, arr2)

ValueError: operands could not be broadcast together with shapes (1,3) (3,4) 

In [ ]:
# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[4, 5, 6],
                [7, 8, 9],
                [10, 11, 12],
                [13, 14, 15]])
arr2 + arr1

ValueError: operands could not be broadcast together with shapes (4,3) (1,4) 

In [ ]:
# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
arr1 = np.array([[1],[5],[8]])
arr2 = np.array([[4, 5, 6]])
arr1 + arr2

array([[ 5,  6,  7],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[4, 5],
                [7, 8]])
arr1*arr2

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [ ]:
# 41. Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.mean(axis=0)

array([2.5, 3.5, 4.5])

In [ ]:
# 42. Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.max(axis=1)

array([3, 6])

In [ ]:
# 43. For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.argmax(axis=0)

array([1, 1, 1])

In [ ]:
# 44. For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])
np.cumsum(arr, axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [ ]:
# 45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])
np.all(arr % 2 == 0, axis=0)

array([False, False, False])

In [ ]:
# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])
m = 2
n = 3
reshaped_matrix = original_array.reshape(m, n)
reshaped_matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 47. Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
def flatten_matrix(matrix):
    flattened_array = matrix.flatten()
    return flattened_array

In [ ]:
# 48. Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])
np.concatenate((array1, array2), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.array_split(original_array, 3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [ ]:
# 50. Write a function that inserts and then deletes elements from a given array at specified indices.
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

original_array = np.insert(original_array,[2,4],[10,11])
original_array = np.delete(original_array,[1,3])
original_array

array([ 1, 10,  4, 11,  5])

In [ ]:
# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.
arr1 = np.random.randint(1,5)
arr2 = np.arange(1,11)
arr1 + arr2

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [ ]:
# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.
arr1 = np.arange(10,0,-1)
arr2 = np.arange(0,10,1)
arr1-arr2

array([10,  8,  6,  4,  2,  0, -2, -4, -6, -8])

In [ ]:
# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.
arr1 = np.random.randint(1,10)
arr2 = np.arange(1,6)
arr1*arr2

array([ 8, 16, 24, 32, 40])

In [ ]:
# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.
arr1 = np.arange(2,11,2)
arr2 = np.arange(1,6)
arr1/arr2

array([2., 2., 2., 2., 2.])

In [ ]:
# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
 #reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
arr1 = np.arange(1,6)
arr2 = np.arange(5,0,-1)
arr1**arr2

array([ 1, 16, 27, 16,  5])

In [ ]:
# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
def count_substring(string,substring):
  count = 0
  for s in string:
    if substring in s:
      count+=1
  return count

count_substring(('a','b','b','c'),('b'))


2

In [ ]:
import numpy as np

In [ ]:
# 57. Write a function that extracts uppercase characters from a NumPy array of strings.arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
def extract_uppercase_characters(arr):
  uppercase_characters = []
  for s in arr:
    for char in s:
      if char.isupper():
        uppercase_characters.append(char)
  return uppercase_characters
extract_uppercase_characters(arr)

['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']

In [ ]:
# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string
string_array = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
def replace_substring(string_array, old_substring, new_substring):
  new_array = []
  for s in string_array:
    new_s = s.replace(old_substring, new_substring)
    new_array.append(new_s)
  return new_array

replace_substring(string_array, 'OpenAI', 'ChatGPT')

['Hello', 'World', 'ChatGPT', 'GPT']

In [ ]:
# 59. Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
np.char.add(arr1, arr2)

array(['HelloOpen', 'WorldAI'], dtype='<U9')

In [ ]:
# 60. Write a function that finds the length of the longest string in a NumPy array.
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
max_length =max(len(s) for s in arr)
max_length


6

In [ ]:
len(max(arr,key=len))

6

In [ ]:
# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.
dataset = np.random.randint(1,1000,100)
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_dev = np.std(dataset)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

Mean: 460.55
Median: 426.5
Variance: 86167.4275
Standard Deviation: 293.5428886891999


In [ ]:
# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
dataset = np.random.randint(1,100,50)
percentile_25 = np.percentile(dataset,25)
percentile_75 = np.percentile(dataset,75)
print("25th percentile:", percentile_25)
print("75th percentile:", percentile_75)

25th percentile: 27.0
75th percentile: 65.5


In [ ]:
# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.
 # Input array 1
a=np.arange(20,30)

# input array 2
b=np.array([6,11,28,33,59,47,19,44,79,96])

# Using the NumPy corrcoeff() function
x=np.corrcoef(a,b)

# Printing the correlation coefficients:
print(x)

[[1.         0.82490472]
 [0.82490472 1.        ]]


In [ ]:
# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
np.dot(matrix1, matrix2)

array([[19, 22],
       [43, 50]])

In [ ]:
# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.
array1 = np.arange(10,1001,50)
median = np.median(array1)
percentile_90 = np.percentile(array1,90)

print ("median :", median)
print ("percentile_90:", percentile_90)

median : 485.0
percentile_90: 865.0000000000001


In [ ]:
# 66. Create a NumPy array of integers and find the index of a specific element.
num_array = np.array((1,2,3,4,5))
num_array

array([1, 2, 3, 4, 5])

In [ ]:
# 67. Generate a random NumPy array and sort it in ascending order.
num_array = ((2,4,3,1,5,6,8))
np.sort(num_array)

array([1, 2, 3, 4, 5, 6, 8])

In [ ]:
# 68. Filter elements >20  in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])
arr[arr>20]

array([25, 42, 30])

In [ ]:
# 69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])
arr[arr%3==0]

array([12, 15])

In [ ]:
# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
arr[(arr>=20) & (arr<=40)]

array([20, 30, 40])

In [ ]:
# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])
arr.dtype.byteorder

'='

In [ ]:
#72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap()

array([16777216, 33554432, 50331648], dtype=int32)

In [ ]:
#73. For the given NumPy array, swap its byte order without modifying the original array using`newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)
arr.newbyteorder()

array([16777216, 33554432, 50331648], dtype='>i4')

In [ ]:
# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)
arr.newbyteorder()

array([16777216, 33554432, 50331648], dtype='>i4')

In [ ]:
#75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`attribute `byteorder`.
arr = np.array([1, 2, 3], dtype=np.int32)
arr.dtype.byteorder

'='

In [ ]:
#76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
copy_arr = arr1.copy()
copy_arr.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
# the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.
array_ = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
view_slice = array_[1:3,[1,2]]
view_slice.reshape(4)

array([5, 6, 8, 9])

In [ ]:
array_

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
# `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.
array_a = np.array([[1,2,3],[3,5,6],[7,8,9],[10,11,12]])
array_a

view_b = array_a[1:3,[1,2]] #extract a slice
view_b+5 #addition of 5 to copy of array

array_a #checking impact on original array

array([[ 1,  2,  3],
       [ 3,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
# `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
# reflects changes in the original `orig_array`.

orig_array = np.array([[1,2,3,4],[5,6,7,8]])

reshaped_view = orig_array.reshape(4,2) # reshaped original array
reshaped_view[[2],0]=10 #change element in reshaped array
reshaped_view

array([[ 1,  2],
       [ 3,  4],
       [10,  6],
       [ 7,  8]])

In [ ]:
orig_array #check if it also chages in original copy - Changes in original array also

array([[ 1,  2,  3,  4],
       [10,  6,  7,  8]])

In [ ]:
# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
# elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.
data = np.array([[1,2,3,4],
                  [4,5,6,6],
                  [7,8,9,9]])
data_copy = data[data>5] #create numpy copy of elements >5
data_copy

array([6, 6, 7, 8, 9, 9])

In [ ]:
data_copy[2]=10 #replace the element in data_copy
data_copy

array([ 6,  6, 10,  8,  9,  9])

In [ ]:
data #check original data - no change in original copy

array([[1, 2, 3, 4],
       [4, 5, 6, 6],
       [7, 8, 9, 9]])

In [ ]:
# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction
# operations between them.

A = np.array([[1,1,1],
              [1,1,1]])

B = np.array([[2,2,2],[2,2,2]])

C = A + B #addition
print ("Addition:" ,C)

D = A - B #subtraction
print ("subtraction:" ,D)

Addition: [[3 3 3]
 [3 3 3]]
subtraction: [[-1 -1 -1]
 [-1 -1 -1]]


In [ ]:
#82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
C = np.array([[1,2],[3,4],[5,6]])
D = np.array([[1,2,3,4],[5,6,7,8]])
np.dot(C,D)

array([[11, 14, 17, 20],
       [23, 30, 37, 44],
       [35, 46, 57, 68]])

In [ ]:
#83. Create a matrix `E` and find its transpose.
E = np.array([[1,2,3],[4,5,6]])
np.transpose(E)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#84. Generate a square matrix `F` and compute its determinant.
F = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.det(F)

0.0